### ISSUE TITLE
[Request] Maven addition

### ISSUE THREAD

**Issue by samolego** [beabfc/afkdisplay#7]
Hi there!
I'd like to add support for this mod in my mod [AntiLogout](https://modrinth.com/mod/noexits). (it enables players to do /afk)

However, there's no maven listed in readme, also, jitpack doesn't work due to  its [java being outdated](https://jitpack.io/com/github/beabfc/afkdisplay/1.0.1/build.log).

Do you have a maven? If not, could you add jitpack support?
[(you can specify different java for it)](https://raw.githubusercontent.com/samolego/Taterzens/master/jitpack.yml)

**Comment by beabfc** [comment]
Thank you for your feedback! I think adding this mods functionality to AntiLogout would be a great idea.

Unfortunately I'm not very familiar with the Java Ecosystem. I do not have a maven. Would it be enough to add a `jitpack.yml` file with the following content to the root of this repository?

```yml
jdk:
  - openjdk17
```

**Comment by samolego** [comment]
Yes, you create `jitpack.yml`, afaik all this is neede:

```yml
jdk:
  - openjdk17
before_install:
  - export SDKMAN_DIR="/home/jitpack/.sdkman/"
  - source "/home/jitpack/.sdkman/bin/sdkman-init.sh"
  - sdk install java 17.0.1-open
  - sdk use java 17.0.1-open
```
